name: Feature Request
description: Suggest a new feature or enhancement for TicketKit
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature you'd like to see
      placeholder: "Add support for custom field validation rules"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem It Solves
      description: What problem does this feature solve? What use case does it enable?
      placeholder: |
        Currently, there's no way to validate custom fields...
        This makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Add a `validators` option to custom fields:

        ```javascript
        const ticket = await kit.createTicket({
          custom_fields: {
            story_points: 5
          },
          validators: {
            story_points: (value) => value >= 1 && value <= 13
          }
        });
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        - Could manually validate before calling createTicket()
        - Could use a separate validation library

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Nice to have"
        - "Would improve my workflow"
        - "Blocking my use case"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with documentation
        - label: I can help with testing

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples from other libraries, or screenshots
